name: Deploy to Cloud Run (Dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: zaya-backend-dev
  REGION: us-central1
  IMAGE_NAME: zaya-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-${{ github.sha }} .
        docker tag gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-${{ github.sha }} gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-latest
    
    - name: Push Docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-${{ github.sha }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME:dev-${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="ENVIRONMENT=dev" \
          --set-secrets="OPENAI_API_KEY=openai-api-key-dev:latest,FEISHU_APP_ID=feishu-app-id-dev:latest,FEISHU_APP_SECRET=feishu-app-secret-dev:latest,FEISHU_TABLE_APP_TOKEN=feishu-table-app-token-dev:latest,FEISHU_TABLE_ID=feishu-table-id-dev:latest" \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10 \
          --port 8080
    
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --platform managed --region $REGION --format 'value(status.url)')
        echo "Service deployed at: $SERVICE_URL"