name: Deploy to Cloud Run (Production)

on:
  push:
    branches:
      - prod
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: zaya-backend-prod
  REGION: us-central1
  IMAGE_NAME: zaya-backend
  REGISTRY_LOCATION: us-central1
  REPOSITORY: zaya-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGISTRY_LOCATION-docker.pkg.dev
    
    - name: Build Docker image
      run: |
        docker build -t $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-${{ github.sha }} .
        docker tag $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-${{ github.sha }} $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-latest
    
    - name: Push Docker image
      run: |
        docker push $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-${{ github.sha }}
        docker push $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:prod-${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars="ENVIRONMENT=production" \
          --set-secrets="OPENAI_API_KEY=openai-api-key-prod:latest,FEISHU_APP_ID=feishu-app-id-prod:latest,FEISHU_APP_SECRET=feishu-app-secret-prod:latest,FEISHU_TABLE_APP_TOKEN=feishu-table-app-token-prod:latest,FEISHU_TABLE_ID=feishu-table-id-prod:latest" \
          --memory 2Gi \
          --cpu 2 \
          --max-instances 50 \
          --port 8080
    
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --platform managed --region $REGION --format 'value(status.url)')
        echo "Service deployed at: $SERVICE_URL"